#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=mydb
#spring.datasource.username=sa
#spring.datasource.password=1234
#spring.datasource.driver-class-name= com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto=create-drop
#server.port=8080
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=mydb
    username: sa
    password: 1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
application:
  security:
    jwt:
      secret: 254d762d256a3b3f712c3c345c372c5e535a414c2c555e6f315b793c50
      expired:
        access:  1000000 # 15 minutes
        refresh:  2592000000
server:
  port: 8080




